// src/app/admin/scholarships/page.tsx
'use client';

import React, { useState, useMemo } from 'react';
import {
  DollarSign,
  Users,
  AlertTriangle,
  FileText,
  Search,
  ChevronLeft,
  ChevronRight,
  Eye,
  Bell,
  Plus,
} from 'lucide-react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Progress } from '@/components/ui/progress';
import { getInitials } from '@/lib/messages-data';
import { scholarshipsData, getStatusConfig, type StudentPayment } from '@/lib/scholarships-data';
import { useToast } from '@/hooks/use-toast';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';

const ITEMS_PER_PAGE = 10;

const StatCard = ({ title, value, subtitle, icon: Icon, color }: { title: string; value: string; subtitle: string; icon: React.ElementType; color: string; }) => (
    <Card>
        <CardHeader className="pb-2">
            <div className="flex justify-between items-start">
                 <CardTitle className="text-sm font-medium">{title}</CardTitle>
                 <Icon className={`h-5 w-5 ${color}`} />
            </div>
        </CardHeader>
        <CardContent>
            <p className="text-2xl font-bold">{value}</p>
            <p className="text-xs text-muted-foreground">{subtitle}</p>
        </CardContent>
    </Card>
);

export default function AdminScholarshipsPage() {
    const [students, setStudents] = useState<StudentPayment[]>(scholarshipsData);
    const [searchTerm, setSearchTerm] = useState('');
    const [classFilter, setClassFilter] = useState('all');
    const [statusFilter, setStatusFilter] = useState('all');
    const [currentPage, setCurrentPage] = useState(1);
    const [paymentModalStudent, setPaymentModalStudent] = useState<StudentPayment | null>(null);
    const { toast } = useToast();

    const filteredStudents = useMemo(() => {
        return students.filter(student =>
            (student.name.toLowerCase().includes(searchTerm.toLowerCase()) || student.studentId.includes(searchTerm)) &&
            (classFilter === 'all' || student.class.includes(classFilter)) &&
            (statusFilter === 'all' || student.status === statusFilter)
        );
    }, [students, searchTerm, classFilter, statusFilter]);

    const stats = useMemo(() => {
        const totalAmount = students.reduce((acc, s) => acc + s.totalAmount, 0);
        const paidAmount = students.reduce((acc, s) => acc + s.paidAmount, 0);
        const lateCount = students.filter(s => s.status === 'late').length;
        const totalStudents = students.length;
        return {
            total: totalAmount.toLocaleString('fr-FR') + ' FCFA',
            paid: paidAmount.toLocaleString('fr-FR') + ' FCFA',
            remaining: (totalAmount - paidAmount).toLocaleString('fr-FR') + ' FCFA',
            late: lateCount,
            totalStudents: totalStudents,
        };
    }, [students]);

    const totalPages = Math.ceil(filteredStudents.length / ITEMS_PER_PAGE);
    const paginatedStudents = useMemo(() => {
        return filteredStudents.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);
    }, [filteredStudents, currentPage]);

    const handleSendReminder = (studentName: string) => {
        toast({
            title: 'Rappel envoyé !',
            description: `Un rappel de paiement a été envoyé à ${studentName}.`,
        });
    };
    
    const handleRegisterPayment = (studentId: string, amount: number) => {
        setStudents(prev => prev.map(s => {
            if(s.id.toString() === studentId) {
                const newPaidAmount = s.paidAmount + amount;
                let newStatus: 'paid' | 'partial' = 'partial';
                if(newPaidAmount >= s.totalAmount) newStatus = 'paid';
                
                return { ...s, paidAmount: newPaidAmount, status: newStatus, lastPaymentDate: new Date().toISOString().split('T')[0] };
            }
            return s;
        }));
        setPaymentModalStudent(null);
        toast({ title: 'Paiement enregistré !', description: `Le paiement de ${amount.toLocaleString('fr-FR')} FCFA a bien été enregistré.` });
    }

    return (
        <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <StatCard title="Montant Total Attendu" value={stats.total} subtitle={`${stats.totalStudents} étudiants`} icon={DollarSign} color="text-blue-500" />
                <StatCard title="Total Perçu" value={stats.paid} subtitle="Paiements enregistrés" icon={Users} color="text-green-500" />
                <StatCard title="Solde Restant" value={stats.remaining} subtitle="À recouvrer" icon={FileText} color="text-purple-500" />
                <StatCard title="Paiements en Retard" value={stats.late.toString()} subtitle="Étudiants à relancer" icon={AlertTriangle} color="text-red-500" />
            </div>

            <Card>
                <CardHeader>
                    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                        <div>
                            <CardTitle>Suivi de la scolarité</CardTitle>
                            <CardDescription>Consultez et gérez les paiements des étudiants.</CardDescription>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    <div className="flex flex-col sm:flex-row gap-4">
                        <div className="relative flex-1">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"/>
                            <Input placeholder="Rechercher par nom ou matricule..." className="pl-10" value={searchTerm} onChange={e => setSearchTerm(e.target.value)} />
                        </div>
                        <Select value={classFilter} onValueChange={setClassFilter}><SelectTrigger className="w-full sm:w-[200px]"><SelectValue placeholder="Toutes les classes"/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les classes</SelectItem><SelectItem value="L1">Licence 1</SelectItem><SelectItem value="L2">Licence 2</SelectItem><SelectItem value="L3">Licence 3</SelectItem><SelectItem value="M1">Master 1</SelectItem><SelectItem value="M2">Master 2</SelectItem></SelectContent></Select>
                        <Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="w-full sm:w-[180px]"><SelectValue placeholder="Tous les statuts"/></SelectTrigger><SelectContent><SelectItem value="all">Tous les statuts</SelectItem><SelectItem value="paid">Payé</SelectItem><SelectItem value="partial">Partiel</SelectItem><SelectItem value="late">En retard</SelectItem></SelectContent></Select>
                    </div>
                </CardContent>
                <div className="overflow-x-auto">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Étudiant</TableHead>
                                <TableHead>Classe</TableHead>
                                <TableHead>Progression</TableHead>
                                <TableHead>Statut</TableHead>
                                <TableHead className="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {paginatedStudents.map(student => {
                                const status = getStatusConfig(student.status);
                                const progress = Math.min(100, Math.round((student.paidAmount / student.totalAmount) * 100));
                                return (
                                    <TableRow key={student.id} className="even:bg-muted/40">
                                        <TableCell>
                                            <div className="flex items-center gap-3">
                                                <Avatar className="h-10 w-10"><AvatarImage src={student.avatar} /><AvatarFallback>{getInitials(student.name)}</AvatarFallback></Avatar>
                                                <div>
                                                    <p className="font-medium">{student.name}</p>
                                                    <p className="text-xs text-muted-foreground">{student.studentId}</p>
                                                </div>
                                            </div>
                                        </TableCell>
                                        <TableCell>{student.class}</TableCell>
                                        <TableCell>
                                            <div className="flex items-center gap-2">
                                                <Progress value={progress} className="w-24 h-2" />
                                                <span className="text-xs font-mono text-muted-foreground">{progress}%</span>
                                            </div>
                                            <p className="text-xs text-muted-foreground mt-1">{student.paidAmount.toLocaleString('fr-FR')} / {student.totalAmount.toLocaleString('fr-FR')} FCFA</p>
                                        </TableCell>
                                        <TableCell><Badge variant="outline" className={status.color}><status.icon className="mr-1.5 h-3 w-3"/>{status.label}</Badge></TableCell>
                                        <TableCell className="text-right">
                                            <Button variant="ghost" size="icon" onClick={() => setPaymentModalStudent(student)}><Plus className="h-4 w-4"/></Button>
                                            {student.status === 'late' && <Button variant="ghost" size="icon" className="text-destructive" onClick={() => handleSendReminder(student.name)}><Bell className="h-4 w-4"/></Button>}
                                        </TableCell>
                                    </TableRow>
                                );
                            })}
                        </TableBody>
                    </Table>
                </div>
                 <CardFooter className="flex items-center justify-between p-4">
                    <p className="text-sm text-muted-foreground">Affichage de {paginatedStudents.length} sur {filteredStudents.length} étudiants</p>
                    {totalPages > 1 && (
                        <div className="flex items-center gap-2">
                            <Button variant="outline" size="icon" onClick={() => setCurrentPage(p => Math.max(1,p-1))} disabled={currentPage === 1} className="h-8 w-8"><ChevronLeft/></Button>
                            {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
                                <Button key={page} variant={currentPage === page ? 'default' : 'outline'} size="icon" className="h-8 w-8" onClick={() => setCurrentPage(page)}>{page}</Button>
                            ))}
                            <Button variant="outline" size="icon" onClick={() => setCurrentPage(p => Math.min(totalPages, p+1))} disabled={currentPage === totalPages} className="h-8 w-8"><ChevronRight/></Button>
                        </div>
                    )}
                </CardFooter>
            </Card>

            <Dialog open={!!paymentModalStudent} onOpenChange={() => setPaymentModalStudent(null)}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Enregistrer un paiement</DialogTitle>
                        <DialogDescription>Pour {paymentModalStudent?.name} ({paymentModalStudent?.studentId})</DialogDescription>
                    </DialogHeader>
                    <form onSubmit={(e) => {
                        e.preventDefault();
                        const amount = parseFloat((e.target as HTMLFormElement).amount.value);
                        if (paymentModalStudent && amount > 0) {
                            handleRegisterPayment(paymentModalStudent.id.toString(), amount);
                        }
                    }}>
                        <div className="py-4 space-y-4">
                            <div className="text-sm">
                                <p>Total à payer: <span className="font-semibold">{paymentModalStudent?.totalAmount.toLocaleString('fr-FR')} FCFA</span></p>
                                <p>Déjà payé: <span className="font-semibold">{paymentModalStudent?.paidAmount.toLocaleString('fr-FR')} FCFA</span></p>
                                <p>Solde restant: <span className="font-semibold text-red-600">{(paymentModalStudent?.totalAmount ?? 0 - (paymentModalStudent?.paidAmount ?? 0)).toLocaleString('fr-FR')} FCFA</span></p>
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="amount">Montant du versement</Label>
                                <Input id="amount" name="amount" type="number" placeholder="ex: 500000" required/>
                            </div>
                            <div className="space-y-2">
                                 <Label htmlFor="method">Méthode de paiement</Label>
                                 <Select name="method" defaultValue="cash">
                                    <SelectTrigger><SelectValue/></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="cash">Espèces</SelectItem>
                                        <SelectItem value="cheque">Chèque</SelectItem>
                                        <SelectItem value="transfer">Virement bancaire</SelectItem>
                                        <SelectItem value="mobile">Paiement mobile</SelectItem>
                                    </SelectContent>
                                 </Select>
                            </div>
                        </div>
                        <DialogFooter>
                            <DialogClose asChild><Button type="button" variant="ghost">Annuler</Button></DialogClose>
                            <Button type="submit">Enregistrer le paiement</Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </div>
    );
}

// university-erp/frontend/src/app/features/admin/pages/scholarships/scholarships.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Observable, map } from 'rxjs';
import { UniversityService } from '../../../../core/services/university.service';
import { ScholarshipPayment } from '../../../../core/models/university.model';
import { CardComponent } from '../../../../shared/components/ui/card/card.component';
import { ButtonComponent } from '../../../../shared/components/ui/button/button.component';
import { BadgeComponent } from '../../../../shared/components/ui/badge/badge.component';
import { AvatarComponent } from '../../../../shared/components/ui/avatar/avatar.component';
import { ProgressComponent } from '../../../../shared/components/ui/progress/progress.component';
import { InputComponent } from '../../../../shared/components/ui/input/input.component';

@Component({
  selector: 'app-scholarships',
  standalone: true,
  imports: [
    CommonModule, 
    CardComponent, 
    ButtonComponent, 
    BadgeComponent, 
    AvatarComponent,
    ProgressComponent,
    InputComponent
  ],
  template: `
    <div class="space-y-6">
      <div class="flex items-center justify-between">
        <div>
          <h2 class="text-2xl font-bold tracking-tight text-slate-900">Suivi des Paiements & Bourses</h2>
          <p class="text-slate-500">Gérez les frais de scolarité, les bourses et les relances de paiement.</p>
        </div>
      </div>

      <!-- Stats Cards -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <app-card class="bg-blue-600 text-white border-none shadow-blue-200">
          <div class="p-1">
            <p class="text-xs font-medium text-blue-100 uppercase tracking-wider">Total Attendu</p>
            <h3 class="mt-2 text-2xl font-bold">{{ (totalExpected$ | async) | number:'1.0-0' }} FCFA</h3>
            <p class="mt-1 text-[10px] text-blue-200">Revenus prévisionnels 2024</p>
          </div>
        </app-card>

        <app-card>
          <p class="text-xs font-medium text-slate-500 uppercase tracking-wider">Total Perçu</p>
          <h3 class="mt-2 text-2xl font-bold text-green-600">{{ (totalPaid$ | async) | number:'1.0-0' }} FCFA</h3>
          <div class="mt-2 flex items-center gap-2">
            <app-progress [value]="(collectionRate$ | async) || 0" color="success" class="h-1.5"></app-progress>
            <span class="text-[10px] font-bold text-slate-500">{{ (collectionRate$ | async) | number:'1.0-0' }}%</span>
          </div>
        </app-card>

        <app-card>
          <p class="text-xs font-medium text-slate-500 uppercase tracking-wider">Solde Restant</p>
          <h3 class="mt-2 text-2xl font-bold text-slate-900">{{ (totalRemaining$ | async) | number:'1.0-0' }} FCFA</h3>
          <p class="mt-1 text-[10px] text-slate-400">À recouvrer avant Mars 2025</p>
        </app-card>

        <app-card>
          <p class="text-xs font-medium text-slate-500 uppercase tracking-wider">Paiements en Retard</p>
          <h3 class="mt-2 text-2xl font-bold text-red-600">{{ (lateCount$ | async) }}</h3>
          <p class="mt-1 text-[10px] text-red-400 font-medium">Étudiants à relancer d'urgence</p>
        </app-card>
      </div>

      <!-- Main Table -->
      <app-card>
        <div class="mb-4 flex flex-col sm:flex-row gap-4">
          <app-input class="flex-1" placeholder="Rechercher un étudiant..." icon="pi-search"></app-input>
          <select class="rounded-md border border-slate-200 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 outline-none">
             <option value="">Toutes les classes</option>
             <option value="L1">L1</option>
             <option value="L2">L2</option>
             <option value="L3">L3</option>
          </select>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full text-left text-sm text-slate-500">
            <thead class="bg-slate-50 text-xs uppercase text-slate-700 font-semibold border-b border-slate-100">
              <tr>
                <th class="px-6 py-3">Étudiant</th>
                <th class="px-6 py-3">Classe</th>
                <th class="px-6 py-3">Progression</th>
                <th class="px-6 py-3">Statut</th>
                <th class="px-6 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let payment of payments$ | async" class="border-b border-slate-100 bg-white hover:bg-slate-50/50">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <app-avatar [name]="payment.name" [src]="payment.avatar" size="sm"></app-avatar>
                    <div>
                      <div class="font-medium text-slate-900">{{ payment.name }}</div>
                      <div class="text-[10px] text-slate-500 font-mono">{{ payment.studentNumber }}</div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 text-xs font-medium">{{ payment.class }}</td>
                <td class="px-6 py-4">
                  <div class="flex items-center gap-2">
                    <app-progress [value]="getProgress(payment)" [color]="getProgressColor(payment)" class="w-24 h-2"></app-progress>
                    <span class="text-[10px] font-mono font-bold">{{ getProgress(payment) }}%</span>
                  </div>
                  <div class="mt-1 text-[9px] text-slate-400">
                    {{ payment.paidAmount | number:'1.0-0' }} / {{ payment.totalAmount | number:'1.0-0' }} FCFA
                  </div>
                </td>
                <td class="px-6 py-4">
                  <app-badge [variant]="getStatusVariant(payment.status)">
                    {{ getStatusLabel(payment.status) }}
                  </app-badge>
                </td>
                <td class="px-6 py-4 text-right">
                   <div class="flex justify-end gap-1">
                      <app-button variant="ghost" icon="pi-plus-circle" size="sm" class="text-blue-600"></app-button>
                      <app-button *ngIf="payment.status === 'late'" variant="ghost" icon="pi-bell" size="sm" class="text-red-500"></app-button>
                   </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </app-card>
    </div>
  `
})
export class ScholarshipsComponent implements OnInit {
  payments$!: Observable<ScholarshipPayment[]>;
  totalExpected$!: Observable<number>;
  totalPaid$!: Observable<number>;
  totalRemaining$!: Observable<number>;
  lateCount$!: Observable<number>;
  collectionRate$!: Observable<number>;

  constructor(private universityService: UniversityService) {}

  ngOnInit() {
    this.payments$ = this.universityService.getScholarships();

    this.totalExpected$ = this.payments$.pipe(
      map(payments => payments.reduce((acc, p) => acc + p.totalAmount, 0))
    );

    this.totalPaid$ = this.payments$.pipe(
      map(payments => payments.reduce((acc, p) => acc + p.paidAmount, 0))
    );

    this.totalRemaining$ = this.payments$.pipe(
      map(payments => payments.reduce((acc, p) => acc + (p.totalAmount - p.paidAmount), 0))
    );

    this.lateCount$ = this.payments$.pipe(
      map(payments => payments.filter(p => p.status === 'late').length)
    );

    this.collectionRate$ = this.payments$.pipe(
      map(payments => {
        const total = payments.reduce((acc, p) => acc + p.totalAmount, 0);
        const paid = payments.reduce((acc, p) => acc + p.paidAmount, 0);
        return total > 0 ? (paid / total) * 100 : 0;
      })
    );
  }

  getProgress(payment: ScholarshipPayment): number {
    return Math.round((payment.paidAmount / payment.totalAmount) * 100);
  }

  getProgressColor(payment: ScholarshipPayment): any {
    const progress = this.getProgress(payment);
    if (progress >= 100) return 'success';
    if (payment.status === 'late') return 'danger';
    return 'primary';
  }

  getStatusVariant(status: string): any {
    switch (status) {
      case 'paid': return 'success';
      case 'partial': return 'warning';
      case 'late': return 'danger';
      default: return 'secondary';
    }
  }

  getStatusLabel(status: string): string {
    switch (status) {
      case 'paid': return 'Réglé';
      case 'partial': return 'Partiel';
      case 'late': return 'En Retard';
      default: return status;
    }
  }
}
