// src/components/landing/pricing.tsx
import { Button } from "@/components/ui/button";
import { Check } from "lucide-react";

const pricingPlans = [
  {
    name: 'Starter',
    description: 'Pour les petites écoles',
    price: '49€',
    period: 'par mois / jusqu\'à 500 étudiants',
    features: ['Gestion des étudiants', 'Planification de base', 'Support email', 'Stockage 10GB'],
    isPopular: false,
    buttonText: 'Commencer',
    buttonVariant: 'ghost' as const
  },
  {
    name: 'Professional',
    description: 'Pour les universités moyennes',
    price: '149€',
    period: 'par mois / jusqu\'à 5000 étudiants',
    features: ['Toutes les fonctions Starter', 'Analytics IA avancées', 'Gestion financière complète', 'Support prioritaire 24/7', 'Stockage 100GB'],
    isPopular: true,
    buttonText: 'Commencer',
    buttonVariant: 'default' as const
  },
  {
    name: 'Enterprise',
    description: 'Pour les grandes universités',
    price: 'Sur mesure',
    period: 'étudiants illimités',
    features: ['Toutes les fonctions Professional', 'Personnalisation complète', 'Intégrations sur mesure', 'Gestionnaire de compte dédié', 'Stockage illimité'],
    isPopular: false,
    buttonText: 'Nous contacter',
    buttonVariant: 'ghost' as const
  }
];

export default function Pricing() {
  return (
    <section id="prix" className="py-20 bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4">Plans Tarifaires</h2>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            Choisissez le plan qui correspond à la taille de votre établissement
          </p>
        </div>
        <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {pricingPlans.map(plan => (
            <div key={plan.name} className={`bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-lg hover:shadow-xl transition-all ${plan.isPopular ? 'border-2 border-primary relative' : ''}`}>
              {plan.isPopular && (
                <div className="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-primary text-white px-4 py-1 rounded-full text-sm font-semibold">
                  Populaire
                </div>
              )}
              <div className="text-center mb-8">
                <h3 className="text-2xl font-semibold mb-2">{plan.name}</h3>
                <p className="text-gray-600 dark:text-gray-300 mb-4">{plan.description}</p>
                <div className="text-4xl font-bold text-primary mb-2">{plan.price}</div>
                <p className="text-sm text-gray-500 dark:text-gray-400">{plan.period}</p>
              </div>
              <ul className="space-y-3 mb-8">
                {plan.features.map(feature => (
                  <li key={feature} className="flex items-center">
                    <Check className="h-5 w-5 text-green-500 mr-3" />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
              <Button className="w-full" variant={plan.buttonVariant === 'default' ? 'default' : 'secondary'}>{plan.buttonText}</Button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// university-erp/frontend/src/app/landing/components/pricing/pricing.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-landing-pricing',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section id="tarifs" class="py-20 bg-slate-50 dark:bg-gray-900">
      <div class="container mx-auto px-6">
        <div class="text-center mb-16">
          <h2 class="text-4xl font-bold mb-4">Plans Flexibles</h2>
          <p class="text-xl text-gray-600 dark:text-gray-300">Des solutions adaptées à la taille de votre institution</p>
        </div>
        
        <div class="grid md:grid-cols-3 gap-8">
          <div *ngFor="let plan of pricingPlans" class="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-lg border border-gray-100 dark:border-gray-700 hover:border-blue-500 transition-all transform hover:-translate-y-2">
            <h3 class="text-2xl font-bold mb-2">{{plan.name}}</h3>
            <div class="mb-6">
              <span class="text-4xl font-bold text-blue-600">{{plan.price}}</span>
              <span class="text-gray-500">/an</span>
            </div>
            <p class="text-gray-600 dark:text-gray-400 mb-8">{{plan.description}}</p>
            <ul class="space-y-4 mb-8">
              <li *ngFor="let feature of plan.features" class="flex items-center text-sm">
                <i class="pi pi-check text-green-500 mr-2"></i>
                {{feature}}
              </li>
            </ul>
            <button class="w-full py-4 rounded-xl font-semibold transition-all shadow-md {{plan.main ? 'bg-blue-600 text-white hover:bg-blue-700' : 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-white hover:bg-gray-200 dark:hover:bg-gray-600'}}">
              Choisir ce plan
            </button>
          </div>
        </div>
      </div>
    </section>
  `
})
export class LandingPricingComponent {
  pricingPlans = [
    {
      name: 'Standard',
      price: '5M FCFA',
      description: 'Pour les petits établissements ou facultés isolées.',
      features: ['Jusqu\'à 1,000 étudiants', 'Gestion académique de base', 'Support par email', 'Blue AI Lite'],
      main: false
    },
    {
      name: 'Premium',
      price: '15M FCFA',
      description: 'La solution complète pour les universités en croissance.',
      features: ['Étudiants illimités', 'Gestion financière avancée', 'Blue AI Enterprise', 'Support 24/7'],
      main: true
    },
    {
      name: 'Excellence',
      price: 'Sur Devis',
      description: 'Sur mesure pour les grands réseaux universitaires.',
      features: ['Multi-campus', 'Hébergement dédié', 'IA sur mesure', 'Formation sur site'],
      main: false
    }
  ];
}
