// src/components/landing/footer.tsx
import Link from 'next/link';
import { GraduationCap, Facebook, Twitter, Linkedin } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-gray-900 text-white py-16">
      <div className="container mx-auto px-6">
        <div className="grid md:grid-cols-4 gap-8">
          <div>
            <div className="flex items-center space-x-2 mb-6">
              <div className="w-10 h-10 bg-gradient-to-r from-primary to-secondary rounded-lg flex items-center justify-center">
                <GraduationCap className="text-white h-6 w-6" />
              </div>
              <span className="text-2xl font-bold">UNI-VERX</span>
            </div>
            <p className="text-gray-400 mb-4">
              La solution de gestion universitaire intelligente qui révolutionne l'enseignement supérieur.
            </p>
            <p className="text-sm text-gray-500">Un produit de INNOV'KORP</p>
            <div className="flex space-x-4 mt-4">
              <a href="#" className="text-gray-400 hover:text-white transition-colors"><Facebook className="h-5 w-5" /></a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors"><Twitter className="h-5 w-5" /></a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors"><Linkedin className="h-5 w-5" /></a>
            </div>
          </div>
          <div>
            <h4 className="text-xl font-semibold mb-6">Produit</h4>
            <ul className="space-y-3 text-gray-400">
              <li><a href="#" className="hover:text-white transition-colors">Fonctionnalités</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Intégrations</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Sécurité</a></li>
              <li><a href="#" className="hover:text-white transition-colors">API</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-xl font-semibold mb-6">Support</h4>
            <ul className="space-y-3 text-gray-400">
              <li><a href="#" className="hover:text-white transition-colors">Documentation</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Centre d'aide</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Formation</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Communauté</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-xl font-semibold mb-6">Entreprise</h4>
            <ul className="space-y-3 text-gray-400">
              <li><a href="#" className="hover:text-white transition-colors">À propos</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Carrières</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Presse</a></li>
              <li><a href="#" className="hover:text-white transition-colors">Partenaires</a></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-gray-800 mt-12 pt-8 text-center text-gray-400">
          <p>© 2024 UNI-VERX par INNOV'KORP. Tous droits réservés.</p>
        </div>
      </div>
    </footer>
  );
}

// university-erp/frontend/src/app/landing/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-landing-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer class="bg-gray-900 text-white py-12 border-t border-gray-800">
      <div class="container mx-auto px-6">
        <div class="grid md:grid-cols-4 gap-12 mb-12">
          <div class="col-span-2">
             <div class="flex items-center gap-2 mb-6">
              <div class="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center">
                <span class="text-white font-bold text-xl">U</span>
              </div>
              <span class="text-2xl font-bold">UNI-VERX</span>
            </div>
            <p class="text-gray-400 max-w-sm">
              La plateforme ERP intelligente dédiée à l'excellence académique en Afrique et au-delà. Propulsé par Blue AI.
            </p>
          </div>
          
          <div>
            <h4 class="text-lg font-bold mb-6">Liens Rapides</h4>
            <ul class="space-y-4 text-gray-400">
              <li><a href="#fonctions" class="hover:text-blue-500 transition-colors">Fonctionnalités</a></li>
              <li><a href="#tarifs" class="hover:text-blue-500 transition-colors">Tarifs</a></li>
              <li><a href="#temoignages" class="hover:text-blue-500 transition-colors">Témoignages</a></li>
            </ul>
          </div>
          
          <div>
            <h4 class="text-lg font-bold mb-6">Légal</h4>
            <ul class="space-y-4 text-gray-400">
              <li><a href="#" class="hover:text-blue-500 transition-colors">Mentions Légales</a></li>
              <li><a href="#" class="hover:text-blue-500 transition-colors">Politique RGPD</a></li>
              <li><a href="#" class="hover:text-blue-500 transition-colors">Conditions Générales</a></li>
            </ul>
          </div>
        </div>
        
        <div class="pt-8 border-t border-gray-800 text-center text-gray-500 text-sm">
          &copy; 2025 UNI-VERX ERP. Tous droits réservés.
        </div>
      </div>
    </footer>
  `
})
export class LandingFooterComponent {}
