// src/components/landing/header.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { GraduationCap, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLoginModal } from '@/hooks/use-login-modal';

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const { onOpen } = useLoginModal();

  const navLinks = [
    { href: '#fonctions', label: 'Fonctions' },
    { href: '#prix', label: 'Prix' },
    { href: '#temoignages', label: 'Témoignages' },
    { href: '#contact', label: 'Contact' },
  ];

  return (
    <header className="fixed top-0 left-0 right-0 bg-white/95 dark:bg-gray-900/95 backdrop-blur-sm z-50 shadow-sm">
      <nav className="container mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-10 h-10 bg-gradient-to-r from-primary to-secondary rounded-lg flex items-center justify-center">
              <GraduationCap className="text-white h-6 w-6" />
            </div>
            <span className="text-2xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">UNI-VERX</span>
          </Link>
          
          <div className="hidden md:flex items-center space-x-8">
            {navLinks.map((link) => (
              <a key={link.href} href={link.href} className="text-gray-600 dark:text-gray-300 hover:text-primary transition-colors">{link.label}</a>
            ))}
            <Button onClick={onOpen} className="bg-primary hover:bg-secondary text-white px-6 py-2 rounded-lg transition-colors">
              Se connecter
            </Button>
          </div>
          
          <button onClick={() => setIsMenuOpen(!isMenuOpen)} className="md:hidden text-gray-600 dark:text-gray-300">
            {isMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </button>
        </div>
        
        {isMenuOpen && (
          <div className="md:hidden mt-4 pb-4 border-t border-gray-200 dark:border-gray-700">
            <div className="flex flex-col space-y-4 pt-4">
              {navLinks.map((link) => (
                <a key={link.href} href={link.href} onClick={() => setIsMenuOpen(false)} className="text-gray-600 dark:text-gray-300 hover:text-primary transition-colors">{link.label}</a>
              ))}
              <Button onClick={() => { onOpen(); setIsMenuOpen(false); }} className="bg-primary hover:bg-secondary text-white px-6 py-2 rounded-lg transition-colors text-left justify-start">
                Se connecter
              </Button>
            </div>
          </div>
        )}
      </nav>
    </header>
  );
}

// university-erp/frontend/src/app/landing/components/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-landing-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <header class="fixed top-0 w-full z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md border-b border-gray-100 dark:border-gray-800">
      <nav class="container mx-auto px-6 py-4 flex items-center justify-between">
        <div class="flex items-center gap-2">
          <div class="w-10 h-10 bg-primary rounded-xl flex items-center justify-center">
            <span class="text-white font-bold text-xl">U</span>
          </div>
          <span class="text-2xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            UNI-VERX
          </span>
        </div>
        
        <div class="hidden md:flex items-center gap-8">
          <a href="#fonctions" class="text-gray-600 dark:text-gray-300 hover:text-primary transition-colors">Fonctionnalités</a>
          <a href="#tarifs" class="text-gray-600 dark:text-gray-300 hover:text-primary transition-colors">Tarifs</a>
          <a href="#temoignages" class="text-gray-600 dark:text-gray-300 hover:text-primary transition-colors">Témoignages</a>
          <a routerLink="/login" class="bg-primary text-white px-6 py-2 rounded-lg hover:bg-secondary transition-all shadow-md">
            Connexion
          </a>
        </div>
      </nav>
    </header>
  `
})
export class LandingHeaderComponent {}
